### PR TITLE
Travis and Windows Fixes

### PR DESCRIPTION
**Pull request by nathanhilbert**
I wasn't aware that I could do a PR of a PR branch.  I would have contributed earlier.  With the following edits, tests run without error in Windows, Ubuntu 14.04, and Travis.

### CODE REVIEW

**Comment by pudo** [comment]
Wow, a meta-pull request. Let me review. 

2699087-9027117668-tim-a

**Comment by pudo** [comment]
Thanks again for those fixes, I'm still pleasantly surprised this whole thing flies on Windows at all. 

btw. interesting to see contributions via @USStateDept. Will you be available for the next developers meeting so that we can learn a bit about your use cases/requirements?

**Comment by nathanhilbert** [comment]
Thanks for merge.  Yes, I was planning on at least lurking on the OS dev meeting on the 8th, but happy to share.  I've been doing a little work on the [ETL](https://github.com/USStateDept/openspending/commits/statedev) and [data management UI/UX](https://github.com/USStateDept/databankjs) and have some [tech notes](https://github.com/USStateDept/openspending/wiki/Ideas-for-Dev-of-OS-for-State) jotted down.  I should probably expand on this to actually include the use cases and requirements.

**Comment by pudo** [comment]
Wow, this looks incredibly in line with what I want to do for @CodeForAfrica: better, simpler ETL, better aggregations. I also see that you are a fellow user of angular, so we seem to overlap in how we want to get there. 

For what it's worth, I'm currently considering a series of further major changes:

* Switch the backend to ``cubes`` (https://github.com/DataBrewery/cubes) and switch to a modularized ETL process using something like ``loadkit`` (https://github.com/pudo/loadkit). 
* Make the data model richer in terms of dataset metadata and dimension metadata (e.g. your geographic breakdown!). 
* Re-write the data modelling/loading app in angular against a well-defined REST API.
* Re-write the data vis/embed bits in angular and d3, against cubes (and OpenSpending metadata). 

I'm not sure I have time for all of them, but maybe we could get it done together? 

Hoping to speak on the 8th.

**Comment by nathanhilbert** [comment]
That's great!  Our lists line up with the exception of cubes (I'm sure you
have a good reason for this though) and the ETL process.  I'll have about
50% of my time devoted to our project using OS until July when we have to
deliver a production level site, so I can certainly contribute where
appropriate.
I can go into more detail about how our ETL process is slightly different
and specifics about geography, use cases etc.  Do you recommend a good spot
to continue this discussion for the OS folks?  I'm sure an obscure pull
request is not a good location.

**Comment by pudo** [comment]
Are you on the ``openspending-dev`` list? I've been trying to keep that up
to date, and I think it reaches all the relevant people.

**Pull request merged**
